# src/main/resources/application.yaml

data:
  trainers:
    path: classpath:data/trainers.json
  trainees:
    path: classpath:data/trainees.json
  trainings:
    path: classpath:data/trainings.json
  trainingtypes:
    path: classpath:data/trainingTypes.json

#Database configuration
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/gymcrm_db
  username: postgres
  password: myadmin1234


#Hibernate configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

#Flyway
flyway:
  locations: classpath:db/migration




